### ISSUE TITLE
Added features.

### ISSUE THREAD

**Issue by ladhim** [ahmedayman4a/1Hack#1]
Try adding a refresh button.
Also, open external links in user's default browsers!

**Comment by ahmedayman4a** [comment]
Yeah I will add a refresh button in the context menu.

> Also, open external links in user's default browsers!

I just noticed that external links open in default browser AND in the app.

**Comment by ahmedayman4a** [comment]
Added a refresh button and now opens external links in user's default browsers with version 1.0.1
Thank you for reporting the issue and helping me improve the program
