### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by camlogical** [ahmedayman4a/1Hack#2]
Issue:
1. Please fix on redirect open link because when I click on a link then it will open on web browser instead in app.

Suggest:
1. Please add title bar. and add maximize function.  
2. Add back, forward, reload function (Icon)
3. please disable right click (for some reason)

**Comment by ahmedayman4a** [comment]
> Please fix on redirect open link because when I click on a link then it will open on web browser instead in app.

Working on a fix #1

> Please add title bar. and add maximize function.

The window is already maximized

> Add back, forward, reload function (Icon)

* You can already do that from the right click menu. 

* Reload will be added. 

* Adding refresh,forward and back buttons to the UI will be tedious as there is no space for that but I might add a back button only.

> please disable right click

Then how can you go back , forward and refresh ?

**Comment by camlogical** [comment]
1. For maximize sometime working on fresh install after open a few times I didn’t get fullscreen. That why I request you to add title bar with minimize maximize and close button.
2. It ok for right click but I request you to add icon of back forward and reload instead because i got inspect elements on right click.

**Comment by ahmedayman4a** [comment]
1. Are you using the released version or building your own because Inspect Element shouldn't appear in the released version. It doesn't appear for me.
2. As for the maximize problem I thought I already fixed it. Are you using linux?

**Comment by camlogical** [comment]
I using window 10 but i got those bug and i have no idea on it. No title bar, it not feel comfortable because I can’t resize it or take it to other side of screen easily.

**Comment by ahmedayman4a** [comment]
Okay , I will add a title bar with version 1.1.0

**Comment by ahmedayman4a** [comment]
Added a refresh button and fixed opening in default browser.
Will add a title bar with version 1.1.0 and possibly add back and forward buttons
Thank you for reporting the issue and helping me improve the program

**Comment by camlogical** [comment]
Thank you for your improvements. But i Got some error.
1. Maximize work only on fresh install. Next open it not show in full screen
2. After click close button it doesn’t close app but it hide on task bar.

**Comment by ahmedayman4a** [comment]
> Maximize work only on fresh install. Next open it not show in full screen

I can't reproduce the error but I will try to look for a fix on the internet

> After click close button it doesn’t close app but it hide on task bar.
That's intentional so that you get notifications. If you want to quit the app, right click the icon in the taskbar then click on quit
