### ISSUE TITLE
Status menu icon too big [mac os]

### ISSUE THREAD

**Issue by ayush5harma** [ahmedayman4a/1Hack#4]
A status menu icon for the Mac version to replace this.
![Screenshot 2020-04-08 at 7 12 14 PM](https://user-images.githubusercontent.com/47772616/78791019-f93c7680-79cc-11ea-955d-c96ffac1af54.png)

**Comment by ahmedayman4a** [comment]
In this screenshot the 1Hack icon is fixed. 
![Screenshot 2020-04-08 at 8 14 51 PM](https://user-images.githubusercontent.com/47772616/78797786-d1054580-79d5-11ea-95c6-94a0c5999144.png)
Does this mean this issue is fixed on its own or you tried a fix that worked?

**Comment by ayush5harma** [comment]
I modified the tray icon in the resources.I also found fix for the dock
issue currently trying that.I will pull it if it works and send you the new
app build.

**Comment by ahmedayman4a** [comment]
I invited you as a collaborator
You can read more about this repository's branch design [here](https://nvie.com/posts/a-successful-git-branching-model/)
In short commit changes to release-1.1.0
which will be merged to master and develop
