### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by ghost** [ahmedayman4a/1Hack#5]
1. The Zoom option under the Window menu does the window minimize and maximize function. It's apt to rename the menu from "Zoom" to "Resize Window"

2. Clicking an Ad - The Ad is opened in the same window. There's a option to go back on right click. But for a new user, It'll be difficult to navigate back to the 1Hack page as he is not aware of the functionality. It's better to open the ads in a new default browser tab.

3. Keep Forward/Back button in the top of the dialog window.

**Comment by ahmedayman4a** [comment]
> Keep Forward/Back button in the top of the dialog window.

I will redesign the whole top part of the app and add a back and forward button

> Clicking an Ad - The Ad is opened in the same window. There's a option to go back on right click. But for a new user, It'll be difficult to navigate back to the 1Hack page as he is not aware of the functionality. It's better to open the ads in a new default browser tab.

This is because google forces the ads to open in the same window and opening in a new tab or window is against their policy

> The Zoom option under the Window menu does the window minimize and maximize function. It's apt to rename the menu from "Zoom" to "Resize Window"

Maybe in the future - No promises

**Comment by ghost** [comment]
Thanks!
